### ISSUE TITLE
[bug] Discrepancy in uploadUrl

### ISSUE THREAD

**Issue by nihal-projectolympus** [Mastersam07/firebase-app-distribution-action#7]
Hello, I was trying to use this action for uploading an apk and it did not work, but the workflow completed successfully. 
Looks like the uploadUrl is different from the one mentioned on the documentation:

Firebase Documentation:
https://firebase.google.com/docs/reference/app-distribution/rest/v1/upload.v1.projects.apps.releases/upload

index.js
https://github.com/Mastersam07/firebase-app-distribution-action/blob/00408fa8eae1de7c7adee8c3c96f4aec233e4b93/src/index.js#L38

Solution:
1. Update the uploadUrl to match with the documentation
2. Validate the response from the API call and throw errors on upload failure

**Comment by Mastersam07** [comment]
Hi, thanks for reporting this.

A PR has been raised to address this in #18 .

**Comment by Mastersam07** [comment]
Feel free to reopen if issue persists.
